export const CART_ITEM_DECREMENT = "CART_ITEM_DECREMENT";
export const CART_ITEM_INCREMENT = "CART_ITEM_INCREMENT";
export const CART_ITEM_SEARCH_TEXT = "CART_ITEM_SEARCH_TEXT";
export const CART_ITEM_ADD_ITEM = "CART_ITEM_ADD_ITEM";